tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
brew "ansible"
brew "arping"
brew "glib"
brew "cmatrix"
brew "gmp"
brew "coreutils"
brew "exiftool"
brew "fdupes"
brew "gnutls"
brew "gobject-introspection"
brew "harfbuzz"
brew "srt"
brew "ffmpeg"
brew "fping"
brew "hping"
brew "htop"
brew "libheif"
brew "python@3.8"
brew "imagemagick"
brew "ipcalc"
brew "iperf3"
brew "ipmitool"
brew "iproute2mac"
brew "jq"
brew "libssh"
brew "mas"
brew "mpc"
brew "mpfr"
brew "mtr"
brew "mysql-client"
brew "ncrack"
brew "net-snmp"
brew "nkf"
brew "nmap"
brew "node"
brew "nodebrew"
brew "pwgen"
brew "pyenv"
brew "reattach-to-user-namespace"
brew "rename"
brew "speedtest-cli"
brew "telnet"
brew "tldr"
brew "tmux"
brew "tree"
brew "w3m"
brew "wget"
brew "yarn"
brew "youtube-dl"
brew "yt-dlp"
cask "boostnote"
cask "iterm2"
cask "mactex-no-gui"
cask "mono-mdk-for-visual-studio"
cask "visual-studio-code"
cask "wireshark"
mas "Citrix Secure Access", id: 1338991513
mas "LINE", id: 539883307
mas "Microsoft Remote Desktop", id: 1295203466
mas "Snippety", id: 1530751461
mas "WireGuard", id: 1451685025
mas "Xcode", id: 497799835
