[[plugins]]
repo = 'gabrielelana/vim-markdown'
desc = "Markdown syntax highlighting / support indent/unindent"
on_ft = ['markdown']

[[plugins]]
repo = 'Townk/vim-autoclose'
desc = "Inserts matching bracket, paren, brace or quote"

[[plugins]]
repo = 'github/copilot.vim'
desc = "A Vim/Neovim plugin for GitHub Copilot"

[[plugins]]
repo = 'vim-airline/vim-airline'
desc = "lean & mean status/tabline for vim that's light as air"

[[plugins]]
repo = 'vim-airline/vim-airline-themes'
desc = "A collection of themes for vim-airline"

[[plugins]]
repo = 'tomtom/tcomment_vim'
desc = "An extensible & universal comment vim-plugin that also handles embedded filetypes"
