[[plugins]]
repo = 'gabrielelana/vim-markdown'
desc = "Markdown syntax highlighting / support indent/unindent"
on_ft = ['markdown']

[[plugins]]
repo = 'Townk/vim-autoclose'
desc = "Inserts matching bracket, paren, brace or quote"

[[plugins]]
repo = 'github/copilot.vim'
desc = "A Vim/Neovim plugin for GitHub Copilot"

[[plugins]]
repo = 'vim-airline/vim-airline'
desc = "lean & mean status/tabline for vim that's light as air"

[[plugins]]
repo = 'vim-airline/vim-airline-themes'
desc = "A collection of themes for vim-airline"

[[plugins]]
repo = 'tomtom/tcomment_vim'
desc = "An extensible & universal comment vim-plugin that also handles embedded filetypes"

[[plugins]]
repo = 'airblade/vim-gitgutter'
desc = "A Vim plugin which shows a git diff in the gutter (sign column) and stages/undoes hunks"

[[plugins]]
repo = 'w0rp/ale'
desc = "Asynchronous Lint Engine for Vim and NeoVim with support for many languages"
